### ISSUE TITLE
Overlap between Synthetic and Natural

### ISSUE THREAD

**Issue by KazutoshiShinoda** [noiseQA/NoiseQA#2]
Hi, thank you for releasing the interesting dataset.

I have found some overlapping qa pairs between Synthetic and Natural.
For example, both xquad-asr-natural.json and xquad-asr-synthetic.json have this QA pair in common:
```
{"question": "how many points did the Panthers defense surrender", "id": "56beb4343aeaaa14008c925b", "answers": [{"text": "308", "answer_start": 34}]}
```

Is the overlap intended or unintended?
It would be appreciated if you could check it out.
Thank you very much.

**Comment by AbhilashaRavichander** [comment]
Hi, thank you for your interest in our work!

The overlap you mention is expected. This example looks like a case where the ASR system transcribed the input relatively accurately for both a TTS voice and a human voice (the original input was "How many points did the Panthers defense surrender?"). Please let us know if you have any questions!

**Comment by KazutoshiShinoda** [comment]
Thank you for the informative answer!
I can understand it well.
